[build]
target = ["aarch64-unknown-linux-musl"]
# #target = ["aarch64-unknown-linux-musl", "x86_64-unknown-linux-gnu"]
#
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

# [target.x86_64-unknown-linux-gnu]
# linker = "x86-64-linux-gnu-gcc"
