{{- if .Values.agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesh-cni.agent.serviceAccountName" . }}
  labels:
    {{- include "mesh-cni.agent.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.agent.serviceAccount.automount }}
{{- end }}
