apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesh-cni.fullname" . }}-agent-config
  labels:
    {{- include "mesh-cni.agent.labels" . | nindent 4 }}
data:
  clusters-config.yaml: |
{{- .Values.agent.clustersConfig | toYaml | nindent 4 }}
