apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mesh-cni.fullname" . }}-agent
  labels:
    {{- include "mesh-cni.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mesh-cni.agent.selectorLabels" . | nindent 6 }}
  {{- with .Values.agent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mesh-cni.agent.labels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if not .Values.agent.useCiliumRedirect }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mesh-cni.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      initContainers:
        - name: mount-bpf
          command:
          - /bin/bash
          - -c
          - --
          args:
          - 'mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpffs /sys/fs/bpf'
          securityContext:
            privileged: true
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          volumeMounts:
          - mountPath: /sys/fs/bpf
            name: bpf 
            mountPropagation: Bidirectional
      containers:
        - name: {{ .Chart.Name }}
          args:
          - agent
          - --cluster-url={{ .Values.agent.clusterURL }}
          - --metrics-address=0.0.0.0:{{ .Values.agent.metrics.port }}
          - --cni-bin-dir={{ .Values.agent.cniBinDir }}
          - --cni-conf-dir={{ .Values.agent.cniConfDir }}
          - --cni-plugin-log-dir={{ .Values.agent.cniPluginLogDir }}
          - --agent-socket-path={{ .Values.agent.socketPath }}
          {{- if .Values.agent.chained }}
          - --chained
          {{- end }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- with .Values.agent.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.agent.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.agent.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.agent.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /sys/fs/bpf
            name: bpf 
            mountPropagation: HostToContainer
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /var/run/mesh/netns
            name: netns
            mountPropagation: HostToContainer
          - mountPath: /host/opt/cni/bin
            name: cni-bin
          - mountPath: /host/etc/cni/net.d
            name: cni-conf
          - mountPath: /host/var/log
            name: plugin-logs
          - mountPath: /var/run/mesh
            name: socket
          {{- with .Values.agent.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
        name: bpf
      - hostPath:
          path: /sys/fs/cgroup
          type: DirectoryOrCreate
        name: cgroup
      - hostPath:
          path: /var/run/netns
          type: DirectoryOrCreate
        name: netns
      - hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-bin
      - hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate
        name: cni-conf
      - hostPath:
          path: /var/log
          type: DirectoryOrCreate
        name: plugin-logs
      - hostPath:
          path: /var/run/mesh
          type: DirectoryOrCreate
        name: socket
      {{- with .Values.agent.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
        {{- with .Values.agent.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - operator: Exists
