apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mesh-cni.fullname" . }}-controller-config
  labels:
    {{- include "mesh-cni.controller.labels" . | nindent 4 }}
data:
  clusters-config.yaml: |
{{- .Values.controller.clustersConfig | toYaml | nindent 4 }}
