apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "homelab-cni.fullname" . }}-agent
  labels:
    {{- include "homelab-cni.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "homelab-cni.agent.selectorLabels" . | nindent 6 }}
  {{- with .Values.agent.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homelab-cni.agent.labels" . | nindent 8 }}
        {{- with .Values.agent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if not .Values.agent.useCiliumRedirect }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homelab-cni.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - controller
          - --metrics-address=0.0.0.0:{{ .Values.agent.metrics.port }}
          - --cluster-id={{ .Values.agent.cluster.id }}
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- with .Values.agent.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.agent.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.agent.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.agent.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.agent.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.agent.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
        {{- with .Values.agent.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - operator: Exists
