name: Rust
on:
  pull_request:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: install build-essentials
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install build-essential gcc-aarch64-linux-gnu protobuf-compiler -y
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy,rustfmt
        targets: "aarch64-unknown-linux-musl"
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src,clippy
        targets: "aarch64-unknown-linux-musl"
    # - name: Install bpf-linker
    #   run: cargo install bpf-linker --locked
    # - name: Build
    #   run: cargo build
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
