name: Rust
on:
  pull_request:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: mesh-cni-runners
    steps:
    - uses: actions/checkout@v4
    - name: install build-essentials
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install build-essential gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu -y
    - name: install protoc
      run: |
        PB_REL="https://github.com/protocolbuffers/protobuf/releases"
        curl -LO $PB_REL/download/v30.2/protoc-30.2-linux-x86_64.zip
        unzip protoc-30.2-linux-x86_64.zip -d $HOME/.local
        export PATH="$PATH:$HOME/.local/bin"

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy,rustfmt
        targets: aarch64-unknown-linux-musl,x86_64-unknown-linux-gnu
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src,clippy
        targets: aarch64-unknown-linux-musl,x86_64-unknown-linux-gnu
    - name: Install bpf-linker
      run: cargo install bpf-linker --locked
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --target x86_64-unknown-linux-gnu --verbose
